# Generated by Django 5.2.5 on 2025-08-21 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FLNAngazaQuizzes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('grade_id', models.IntegerField(null=True)),
                ('strand_id', models.IntegerField(null=True)),
                ('substrand_id', models.IntegerField(null=True)),
                ('lesson_id', models.IntegerField(null=True)),
                ('quiz_type', models.CharField(max_length=255)),
                ('question', models.TextField()),
                ('question_type', models.CharField(max_length=255)),
                ('question_sound', models.TextField(null=True)),
                ('options', models.JSONField()),
                ('answer_sound', models.TextField(null=True)),
                ('hint', models.CharField(max_length=255, null=True)),
                ('taxonomy_tag', models.CharField(max_length=255, null=True)),
                ('day', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fln_angaza_quizzes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FLNUserResponses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('quiz_id', models.IntegerField()),
                ('selected_option', models.CharField(max_length=1)),
                ('is_correct', models.BooleanField()),
                ('attempt_number', models.IntegerField(default=1)),
                ('response_time', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_id', models.CharField(max_length=255, null=True)),
                ('device_info', models.JSONField(null=True)),
                ('grade_id', models.IntegerField()),
                ('strand_id', models.IntegerField(null=True)),
                ('substrand_id', models.IntegerField(null=True)),
                ('lesson_id', models.IntegerField(null=True)),
                ('quiz_type', models.CharField(max_length=50)),
                ('taxonomy_tag', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'fln_user_responses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField(null=True)),
                ('subtopic_id', models.IntegerField(null=True)),
                ('subject_id', models.IntegerField(null=True)),
                ('quiz_id', models.IntegerField(null=True)),
                ('student_id', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'question_answers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QuizQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtopic_id', models.CharField(max_length=255)),
                ('subject_id', models.IntegerField(null=True)),
                ('question', models.CharField(max_length=255)),
                ('option_a', models.CharField(max_length=255)),
                ('option_b', models.CharField(max_length=255)),
                ('option_c', models.CharField(max_length=255)),
                ('option_d', models.CharField(max_length=255)),
                ('option_a_explanation', models.CharField(max_length=255)),
                ('option_b_explanation', models.CharField(max_length=255)),
                ('option_c_explanation', models.CharField(max_length=255)),
                ('option_d_explanation', models.CharField(max_length=255)),
                ('answer', models.CharField(max_length=255)),
                ('additional_notes', models.CharField(max_length=255)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('question_level', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'quizq_questions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Schools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=255)),
                ('school_code', models.CharField(max_length=255)),
                ('county_id', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'schools',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StrandActivities',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('subtopic_id', models.CharField(max_length=255)),
                ('subject_id', models.IntegerField(null=True)),
                ('score', models.IntegerField(null=True)),
                ('topic_id', models.IntegerField(null=True)),
                ('class', models.IntegerField()),
                ('taxonomy_tag', models.CharField(max_length=255)),
                ('explanation', models.CharField(max_length=255)),
                ('answer', models.CharField(max_length=255)),
                ('key_word', models.CharField(max_length=255)),
                ('question', models.CharField(max_length=255)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'strand_activities_assessments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subtopics',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('topic_id', models.IntegerField(null=True)),
                ('subtopic_name', models.CharField(max_length=255)),
                ('subject_id', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'subtopics',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('school_code', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
