# Generated by Django 5.2.5 on 2025-08-21 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE TABLE IF NOT EXISTS fln_user_responses (
                id INT AUTO_INCREMENT PRIMARY KEY,
                user_id INT NOT NULL,
                quiz_id INT NOT NULL,
                selected_option VARCHAR(1) NOT NULL,
                is_correct BOOLEAN NOT NULL,
                attempt_number INT DEFAULT 1,
                response_time INT NULL,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                session_id VARCHAR(255) NULL,
                device_info JSON NULL,
                grade_id INT NOT NULL,
                strand_id INT NULL,
                substrand_id INT NULL,
                lesson_id INT NULL,
                quiz_type VARCHAR(50) NOT NULL,
                taxonomy_tag VARCHAR(50) NULL,
                INDEX idx_user_id (user_id),
                INDEX idx_quiz_id (quiz_id),
                INDEX idx_created_at (created_at),
                INDEX idx_grade_id (grade_id),
                INDEX idx_strand_id (strand_id),
                INDEX idx_substrand_id (substrand_id),
                INDEX idx_quiz_type (quiz_type),
                INDEX idx_taxonomy_tag (taxonomy_tag)
            );
            """,
            "DROP TABLE IF EXISTS fln_user_responses;"
        )
    ]
