# Generated by Django 5.2.5 on 2025-08-21 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20250821_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='FLNUserThresholds',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('quiz_type', models.CharField(max_length=50)),
                ('recommendation_threshold', models.FloatField(default=0.6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fln_user_thresholds',
                'managed': True,
                'indexes': [models.Index(fields=['user_id'], name='fln_user_th_user_id_abd62a_idx'), models.Index(fields=['quiz_type'], name='fln_user_th_quiz_ty_0ee24f_idx')],
                'unique_together': {('user_id', 'quiz_type')},
            },
        ),
    ]
