# Generated by Django 5.2.5 on 2025-08-21 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_flnuserthresholds'),
    ]

    operations = [
        migrations.CreateModel(
            name='FLNUserThresholdHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('quiz_type', models.CharField(max_length=50)),
                ('old_threshold', models.FloatField()),
                ('new_threshold', models.FloatField()),
                ('reason', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'fln_user_threshold_history',
                'managed': True,
                'indexes': [models.Index(fields=['user_id'], name='fln_user_th_user_id_651d2a_idx'), models.Index(fields=['quiz_type'], name='fln_user_th_quiz_ty_9b0c83_idx'), models.Index(fields=['created_at'], name='fln_user_th_created_825c30_idx')],
            },
        ),
    ]
